spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pen-processor-order
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Pode ser update, create, create-drop ou validate
    show-sql: true  # Exibe as queries no console

aws:
  sns:
    endpoint: http://localhost:4566
    topic-name: factory-topic
    credential:
      accessKey: test
      secretKey: test
  region: us-east-1
  sqs:
    endpoint: http://localhost:4566
    queue: payment-validator
    listener: payment-notification

server:
  name: Processor Order
  port: 8090