server:
  name: pen-processor-order
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pen-processor-order
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true