spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pen-processor-order
aws:
  sns:
    endpoint: http://localhost:4566
    topic-name: factory-topic
    credential:
      accessKey: test
      secretKey: test
  region: us-east-1


server:
  name: Processor Order
  port: 8090

