spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pen-processor-order
some-key:
  property1: Valor do servico
  property2: XOPTO

sns:
  url: http://localhost:4566
  credential:
    access_key_id: fakeAccessKey
    secret_access_key: fakeSecretKey

server:
  name: Processor Order
  port: 8090