services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4575:4575"
    environment:
      - SERVICES=sns,sqs,secretsmanager,ssm
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - "./init-scripts:/etc/localstack/init/ready.d"
    networks:
      - localstack-network
    command: ["/bin/bash", "/etc/localstack/init/ready.d/setup-localstack.sh"]

  # Outros serviços...


  pen-factory-db:
    image: postgres:15
    container_name: factory-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pen-factory
    ports:
      - "5432:5432"
    networks:
      - localstack-network
    volumes:
      - factory-db-data:/var/lib/postgresql/data

  pen-order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pen-processor-order
    ports:
      - "5433:5432"
    networks:
      - localstack-network
    volumes:
      - order-db-data:/var/lib/postgresql/data

#  #config-server
#  ms-config-server:
#    container_name: ms-config-server
#    build:
#      context: ./pen-config-server
#      dockerfile: Dockerfile
#    volumes:
#      - ./config-server/target:/tmp/config-server
#    environment:
#      - AWS_SQS_ENDPOINT=http://localstack:4566
#      - AWS_SNS_ENDPOINT=http://localstack:4566
#      - AWS_REGION=us-east-1
#    ports:
#      - "8888:8888"
#    depends_on:
#      - localstack
#    networks:
#      - localstack-network
#
#  ms-factory:
#    container_name: ms-factory
#    build:
#      context: ./pen-factory/factory
#      dockerfile: Dockerfile
#    depends_on:
#      - pen-factory-db
#      - ms-config-server
#    networks:
#      - localstack-network

networks:
  localstack-network:
    driver: bridge
volumes:
  factory-db-data:
  order-db-data: