#This file has configs default for all microservices
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create