#This file has configs default for all microservices to access AWS SSM.
aws:
  basic-config:
    #endpoint: http://localstack:4566
    endpoint: http://localhost:4566
    region: us-east-1
    credential:
      accessKey: test
      secretKey: test
