#This file has configs default for all microservices
spring:
  datasource:
    url: jdbc:postgresql://factory-db:5432/pen-factory
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

aws:
  basic-config:
    endpoint: http://localstack:4566
    region: us-east-1
    credential:
      accessKey: test
      secretKey: test
