spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:src/main/java/com/mjp/config_server/workers_configs/ # Diretório local onde estão os arquivos de configuração
  profiles:
    active: native # Ativa o modo nativo para leitura de arquivos locais

server:
  port: 8888
  name: config-server

aws:
  sns:
    endpoint: http://localhost:4566
    topic-name: factory-topic
  sqs:
    queues:
      ball: factory-ball
      ball-support: factory-ball-support
      ball-support-coupler: factory-ball-support-coupler
      ball-support-coupler-ink-tube: factory-ball-support-coupler-ink-tube
      external-tube: factory-external-tube
      ink: factory-ink
      internal-tube: factory-internal-tube
      outer-tube-cover: factory-outer-tube-cover
      tip-cap: factory-tip-cap
  endpoint: http://localhost:4566
  region: us-east-1
  accessKey: test
  secretKey: test
s3:
  bucket-name: config-bucket
