spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:src/main/java/com/mjp/config_server/configs/ # Diretório local onde estão os arquivos de configuração
  profiles:
    active: native # Ativa o modo nativo para leitura de arquivos locais

server:
  port: 8888
  name: config-server
